# see http://about.travis-ci.org/docs/user/languages/php/ for more hints
language: php

# list any PHP version you want to test against
php:
  - 7.0
  - 7.1
  - 7.2

# optionally specify a list of environments, for example to test different RDBMS
env:
  - TRAVIS=true
  - EXECUTE_CS_CHECK=true
  - EXECUTE_TEST_COVERALLS=true

before_install:
  - composer self-update

before_script:
  - composer install --no-interaction --ignore-platform-reqs
  - mysql -e 'create database IF NOT EXISTS test';

script:
- if [[ "$EXECUTE_TEST_COVERALLS" == true ]]; then ./vendor/bin/phpunit --coverage-clover clover.xml ; fi
- if [[ "$EXECUTE_TEST_COVERALLS" != true ]]; then composer test ; fi
- if [[ "$EXECUTE_CS_CHECK" == true ]]; then composer cs-check-travis  ; fi

after_script:
  - if [[ "$EXECUTE_TEST_COVERALLS" == true ]]; then ./vendor/bin/coveralls --root_dir src --config ../.coveralls.yml ; fi